### ISSUE TITLE
Question: Possibility to scroll to first occurrence?

### ISSUE THREAD

**Issue by christiankaindl** [marmelab/highlight-search-term#5]
Hi there, I've come across [your article](https://marmelab.com/blog/2024/04/23/highlight-search-query.html) regarding the CSS Highlighting API and think it is a great approach to text highlighting. I have a use case where the text that is highlighted is potentially further down the page, so user won't notice it without scrolling down themselves.

Is there a way to scroll to the first (or any) of the highlighted texts? I have had a look at the source code, but am not sure how the ranges exactly work, or if they could be used for such a feature.

Thoroughly enjoyed your article, great work!

**Comment by fzaninotto** [comment]
Thanks for your feedback!

There is no built-in way to scroll to the first occurrence. You'll have to fork the lib to add this capability. 

We won't implement that feature in the library because it was designed for filter-as-you-type inputs. Scrolling to the first result may hide the input, even though the user hasn't finished typing their search term. This is a bad UI.

**Comment by christiankaindl** [comment]
Thanks for your answer! I didn't expect that you would add this feature to the library as is, as the use case I have is quite different (only highlight one longer text)—it was more a general question. Though reading through the code again, I think I know how I can proceed.
